name: PowerShell Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install required modules
      shell: pwsh
      run: |
        Install-Module -Name Pester -Force -SkipPublisherCheck
        # Note: WebAdministration module is Windows-only and may not be available in GitHub Actions
        # This is just a syntax check
    
    - name: Check PowerShell syntax
      shell: pwsh
      run: |
        $scriptAnalyzerResult = Invoke-ScriptAnalyzer -Path ./letter-server.ps1 -Severity Error
        if ($scriptAnalyzerResult) {
            Write-Error "Script contains errors"
            $scriptAnalyzerResult | Format-Table
            exit 1
        } else {
            Write-Output "Script syntax check passed"
        }
